name: test

#on:
#  push:
#    branches:
#      - OpenWrt

jobs:
  Self:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
